### ISSUE TITLE
Why does this exist?

### ISSUE THREAD

**Issue by IShaderDeviceMgr** [vincent-yao27/Pornhub-style-icon-generator#2]
Just. WHY???? This isn't even funny, it's just confusing.

**Comment by IShaderDeviceMgr** [comment]
I understand now. It's somewhat amusing.

**Comment by EsmailELBoBDev2** [comment]
this should exist in pornhub comments

**Comment by azalty** [comment]
The best software ever invented

<img width="1457" height="461" alt="Image" src="https://github.com/user-attachments/assets/9f538ba6-affe-4374-93d1-efa03a84cfeb" />
